const talksData = [
  {
    speaker: 'Kevin Sheldrake, Microsoft',
    topic: 'Auto-discovery of Kernel Struct Offsets without BTF',
    youtubeLink: 'https://youtu.be/sZDGyr669kc',
    pdfLink: 'https://drive.google.com/file/d/1KkIyDbicfGzn8C5JJ1h92KusdPKea0T2/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Weilong Cui & Xinyuan Zhang, Google',
    topic: 'Enabling User-space C-native Testing of eBPF Programs',
    youtubeLink: 'https://youtu.be/vkYKXlTQ6cg',
    pdfLink: 'https://drive.google.com/file/d/1szaBxT6lh2ECl_CiyqDS-7RBThY3g2nN/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Sujin Park, Georgia Tech',
    topic: 'Contextual Concurrency Control',
    youtubeLink: 'https://youtu.be/ERFG0vy8nq4',
    pdfLink: 'https://drive.google.com/file/d/1HWkN1RS-6SM3wpjPZGYdx_VZsBiOE7n5/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Simar Singh, Aqua Security',
    topic: 'Why is my eBPF code slow?',
    youtubeLink: 'https://youtu.be/0qkkYpbeBFk',
    pdfLink: 'https://drive.google.com/file/d/17_iy6c4D9KtkkCOLZ0WB_ZvVJEFRr1LK/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Brian Merrell, Walmart',
    topic: 'Running and orchestrating multiple XDP and TC programs',
    youtubeLink: 'https://youtu.be/Fu4L8ewcO70',
    pdfLink: 'https://drive.google.com/file/d/1HkbYumE0nGMBns9YPP0R68J5AV1dnmet/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Daniel Borkmann, Isovalent',
    topic: 'BPF and Spectre: Mitigating transient execution attacks',
    youtubeLink: 'https://youtu.be/6N30Yp5f9c4',
    pdfLink: 'https://drive.google.com/file/d/1exwbhaNYQab_72PSQPqhlIe99u05KA0E/view?usp=sharing',
    keynotes: true,
  },
  {
    speaker: 'Grant Seltzer, Aqua Security',
    topic: 'Compile Once Run Everywhere, the BPF Dream',
    youtubeLink: 'https://youtu.be/x8MMuy6tHyc',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Yehonatan Bruchim, Flow',
    topic: "Speaking the verifier's language - turning from an enemy to a friend",
    youtubeLink: 'https://youtu.be/vNUQkO9r5xs',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Alan Maguire, Oracle',
    topic: 'Data-centric tracing using the BPF Type Format (BTF)',
    youtubeLink: 'https://youtu.be/PRiJYuDMtEQ',
    pdfLink: 'https://drive.google.com/file/d/14Dnue3BXjynqoQxJlD3uYq3rjAaQ8KFw/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Itay Shakury, CNCF Ambassador',
    topic: 'OSS Licensing considerations for eBPF project',
    youtubeLink: 'https://youtu.be/z53T-bxHRMc',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Lorenzo Fontana, Gitpod',
    topic: 'How are BPF helpers made?',
    youtubeLink: 'https://youtu.be/H1pg3PWDbPI',
    pdfLink: 'https://drive.google.com/file/d/1CTz8_5b40uWOAmv91vHwVZmQb7NZAkXW/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Alessandro Decina',
    topic: 'Why Rust is increasingly becoming a great option for writing eBPF programs',
    youtubeLink: 'https://youtu.be/HzXpnxUVZB0',
    pdfLink: 'https://drive.google.com/file/d/1nd9HjtSHtImBkxSDDTG4gUgPnMfBd4O7/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Kyle Quest, All Things Security',
    topic: 'BPF Library Ecosystem Overview in Go, Rust, Python and C',
    youtubeLink: 'https://youtu.be/J5AE93Ah1ew',
    pdfLink: 'https://drive.google.com/file/d/1sT00vkR3ILFwAyAVfONTEak5WBQAThSQ/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Tony Lu, Alibaba',
    topic: 'Track and analyze TCP retransmission with eBPF',
    youtubeLink: 'https://youtu.be/Z4qxd5yYoP4',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Nate Foster, Cornell',
    topic: 'eBPF and P4: Better Together',
    youtubeLink: 'https://youtu.be/CFjZfIJ1NaU',
    pdfLink: 'https://drive.google.com/file/d/1z8H501O5lFsPtp4D3Z2eTCgpy-pGoQnt/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Andrius Grabauskas, Palantir',
    topic: 'Using user-space tracing to solve DNS problems',
    youtubeLink: 'https://youtu.be/0RDp1IPxbg0',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Jed Salazar, Natalia Ivanko, Isovalent',
    topic: 'Keeping your cluster safe from attacks with eBPF',
    youtubeLink: 'https://youtu.be/agN68U8x1go',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Lan Pye, Kentik, Inc.',
    topic: 'Container Level Network Observability with eBPF',
    youtubeLink: 'https://youtu.be/V3vi755gPtk',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Pete Stevenson, Omid Azizi, New Relic',
    topic: 'Continuous Profiling in Production with eBPF',
    youtubeLink: 'https://youtu.be/FGWFM6ly2G8',
    pdfLink: 'https://drive.google.com/file/d/1OCSOp_q3fB-MIjxD6bfGbUVzSbfcQa29/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Andrew Liang, Cruise',
    topic: 'Observing GPU Runtime Behavior Inside a Self-Driving Car',
    youtubeLink: 'https://youtu.be/7bdy2AkRjqE',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Sylvain Hellegouarch, Reliably',
    topic: "Using eBPF as an SRE - A beginner's tale",
    youtubeLink: 'https://youtu.be/PwmCLJQIf3I',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Jaana Dogan, AWS',
    topic: 'eBPF in Microservices Observability',
    youtubeLink: 'https://youtu.be/-I29Cuj2nbI',
    pdfLink: '',
    keynotes: true,
  },
  {
    speaker: 'Brendan Gregg, Netflix',
    topic: 'Getting Started with BPF observability',
    youtubeLink: 'https://youtu.be/bGAVrtb_tFs',
    pdfLink: '',
    keynotes: true,
  },
  {
    speaker: 'Thomas Graf, Isovalent',
    topic: 'The State & Future of eBPF',
    youtubeLink: 'https://youtu.be/vNuEx0wB_-4',
    pdfLink: '',
    keynotes: true,
  },
  {
    speaker: 'Lorenz Bauer & Mark Pashmfouroush, Cloudflare',
    topic: 'Bad middlebox! Catching RFC6437 violations in the wild',
    youtubeLink: 'https://youtu.be/PEzB7av1Qss',
    pdfLink: 'https://drive.google.com/file/d/103c_H10msUmAfimWbeq1xV-OwQW3nEGZ/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Nick Bouliane, DigitalOcean',
    topic: 'Rate limiting access to internal services in a virtual network',
    youtubeLink: 'https://youtu.be/gcHxfhDT-I4',
    pdfLink: 'https://drive.google.com/file/d/1O_3K9YiGprbMDsiSPHr0qqdDeJZKwdjE/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Liz Rice, Isovalent',
    topic: 'A Load Balancer from scratch',
    youtubeLink: 'https://youtu.be/L3_AOFSNKK8',
    pdfLink: 'https://drive.google.com/file/d/1su_UP08xLXbMxYqQq6yH4wgtURK2cjsa/view?usp=sharing',
    keynotes: true,
  },
  {
    speaker: 'Matthew Lenhard, ContainIQ',
    topic: 'Getting started deploying and running BCC in your Kubernetes Cluster',
    youtubeLink: 'https://youtu.be/kRXL3p1sCvU',
    pdfLink: 'https://drive.google.com/file/d/1FzpqdDevzoSS9pXvm77ywpS5UHRSE-rp/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Dave Thaler, Microsoft',
    topic: 'eBPF for Windows',
    youtubeLink: 'https://youtu.be/CEl29L2IDEo',
    pdfLink: '',
    keynotes: true,
  },
  {
    speaker: 'Yiannis Yiakoumis, Selfie Networks',
    topic: 'Networks Tokens with eBPF',
    youtubeLink: 'https://youtu.be/4JymIcyvBMw',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Djalal Harouni, Open Devices GmbH',
    topic: 'BPF to bridge Cloud and IoT Linux Security',
    youtubeLink: 'https://youtu.be/ab8gqVqw_sM',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Brendan Jackman, Google',
    topic: 'Stories from BPF security auditing at Google',
    youtubeLink: 'https://youtu.be/N4YKcMV8iaY',
    pdfLink: 'https://drive.google.com/file/d/1wVbKqk6Eu_NYgiTKCERA2F2sp0sbHkJ2/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Melissa Kilby & Eric Sage, Apple',
    topic: 'Think eBPF for Kernel Security Monitoring - Falco at Apple',
    youtubeLink: 'https://youtu.be/djv6NNYKNAM',
    pdfLink: 'https://drive.google.com/file/d/1klMhTftwAAzowR0bsTmBfvDPgwZUGIx7/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Kanthi Pavuluri & Karan Dalal, Walmart',
    topic: 'High Performance Load Balancing @Walmart',
    youtubeLink: 'https://youtu.be/thmAcyix8FM',
    pdfLink: 'https://drive.google.com/file/d/15C3SEjktdALUa8w9ZwWehURtrmrMKekJ/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Karthikeyan Thangaraj, Verizon Media',
    topic: 'Software L4 Load Balancing for Kubernetes Services at Yahoo! ',
    youtubeLink: 'https://youtu.be/-C86fBMcp5Q',
    pdfLink: '',
    keynotes: false,
  },
  {
    speaker: 'Leonardo Di Donato, Gitpod',
    topic: "Scheduling BPF on Kubernetes doesn't have to be difficult",
    youtubeLink: 'https://youtu.be/zXRhWRK1UjQ',
    pdfLink: 'https://drive.google.com/file/d/1SvhrmUJPNGPLkHWSj5GcKNWdqu82YnIj/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Anthony Comtois, Joseph Samuel, Sebastian Duff, Sky',
    topic: 'eBPF & Cilium at Sky',
    youtubeLink: 'https://youtu.be/u-4naOMfs_w',
    pdfLink: '',
    keynotes: true,
  },
  {
    speaker: 'Shutri Chaturvedi',
    topic:
      'Strengthen Application and Network Layer-Security by Integrating eBPF-Based CNI in Kubernetes',
    youtubeLink: 'https://youtu.be/naov8FarJ-Q',
    pdfLink: 'https://drive.google.com/file/d/12Ftk8wQbDjTil7QWNVTjA8tNACbzSj8M/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Iago López Galeiras & Mauricio Vásquez Bernal, Microsoft',
    topic: 'Extending systemd security features with eBPF',
    youtubeLink: 'https://youtu.be/x7qtSK95tk8',
    pdfLink: 'https://drive.google.com/file/d/1Gq_Mg5PexL9GLUhiK7k3ZETKJQaoApVG/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Daniel Bernier, Bell Canada',
    topic: 'Why eBPF is changing the telco networking space',
    youtubeLink: 'https://youtu.be/fNtG0iHYne4',
    pdfLink: 'https://drive.google.com/file/d/19MLSVqPySQKt7cv8rvlKjkb1IWDoJUQR/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Rafael David Tinico, Aqua Security',
    topic: 'Conntracker: A firewall flow sniffer',
    youtubeLink: 'https://youtu.be/MYnlMrIn-_0',
    pdfLink: 'https://drive.google.com/file/d/1MEJEUnynjkEv827qqckXVA9j_pyKW1tY/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Ian Pye, Kentik Inc.',
    topic: 'Container Level Network Observability with eBPF',
    youtubeLink: 'https://youtu.be/V3vi755gPtk',
    pdfLink: 'https://drive.google.com/file/d/1Qj99h3s5vFXgV_AoC63wGFoQgD4IbYpE/view?usp=sharing',
    keynotes: false,
  },
  {
    speaker: 'Jonathan Perry, Flowmill',
    topic: 'Turnkey network telemetry with the Flowmill Collector',
    youtubeLink: 'https://youtu.be/F1VTRqEC8Ng',
    pdfLink: '',
    keynotes: false,
  },
];

export default talksData;
